version: "2"
services:
  php:
    container_name: php73-apache-example
    volumes:
      - .:/var/www/html
    ports:
      - 8080:80
    build: ./
    image: php73-apache
    environment:
      XDEBUG_CONFIG: "remote_host=192.168.1.156"
  composer:
    restart: 'no'
    image: composer/composer:latest
    command: install
    volumes:
      - .:/app
    user: ${HOST_UID_GID}
